export const ActionTypes = {
    SET_TRANS: "SET_TRANS",
    SET_DATA_LEVEL1: "SET_DATA_LEVEL1",
    SET_ERROR_DATA_LEVEL1:"SET_ERROR_DATA_LEVEL1",
    SET_DATA_SUCCESS_LEVEL1:"SET_DATA_SUCCESS_LEVEL1",
    SET_DATA_LEVEL2:"SET_DATA_LEVEL2",


}